include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - riverpod_lint

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    use_key_in_widget_constructors: false
    prefer_final_fields: true
    unnecessary_breaks: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    curly_braces_in_flow_control_structures: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
